import React, { useEffect } from 'react'
import Head from 'next/head'
import { Box } from '@chakra-ui/react'

export default function Home() {
  useEffect(() => {
    const sliderContainer = document.querySelector('.slider-container')
    const slideRight = document.querySelector('.right-slide')
    const slideLeft = document.querySelector('.left-slide')

    const downButton = document.querySelector('.down-button')
    const upButton = document.querySelector('.up-button')

    const slidesLength = slideLeft.querySelectorAll('div').length

    let activeSlideIndex = 0

    slideLeft.style.top = `-${(slidesLength - 1) * 60}vh`

    // Add EventListener to Buttons
    upButton.addEventListener('click', () => changeSlide('up'))
    downButton.addEventListener('click', () => changeSlide('down'))

    const changeSlide = (direction) => {
      const slideHeight = sliderContainer.clientHeight

      if (direction === 'up') {
        activeSlideIndex++

        if (activeSlideIndex > slidesLength - 1) {
          activeSlideIndex = 0
        }
      } else if (direction === 'down') {
        activeSlideIndex--

        if (activeSlideIndex < 0) {
          activeSlideIndex = slidesLength - 1
        }
      }

      slideRight.style.transform = `translateY(-${
        activeSlideIndex * slideHeight
      }px)`

      slideLeft.style.transform = `translateY(${
        activeSlideIndex * slideHeight
      }px)`
    }

    var autoscroll = setInterval(function () {
      changeSlide('up')

      sliderContainer.onmouseover = function (e) {
        autoscroll = clearInterval(autoscroll)
        console.log('onmouseover')
      }
      sliderContainer.onmouseout = function (e) {
        clearInterval(autoscroll)
        autoscroll = setInterval(function () {
          changeSlide('up')
        }, 3000)
        console.log('onmouseout')
      }
    }, 3000)
  }, [])

  return (
    <>
      <Head>
        <title>Vertical Slider | Javascript</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='slider-container'>
        <div className='left-slide'>
          <Box bgColor={'#de868e'}>
            <h1>Nature Flower</h1>
            <p>All in Pink</p>
          </Box>

          <Box bgColor={'#aaa'}>
            <h1>Mountains</h1>
            <p>With it&apos;s Snow</p>
          </Box>

          <Box bgColor={'#252e33'}>
            <h1>The Castle</h1>
            <p>In the Wildeness</p>
          </Box>

          <Box bgColor={'#2596be'}>
            <h1>The Ocean</h1>
            <p>Big and blue</p>
          </Box>
        </div>
        <div className='right-slide'>
          <Box bgImage={'url(/images/photo1-min.jpg)'}></Box>
          <Box bgImage={'url(/images/photo2-min.jpg)'}></Box>
          <Box bgImage={'url(/images/photo3-min.jpg)'}></Box>
          <Box bgImage={'url(/images/photo4-min.jpg)'}></Box>
        </div>

        <div className='action-buttons'>
          <button className='down-button'>
            <i className='fas fa-arrow-down'></i>
          </button>

          <button className='up-button'>
            <i className='fas fa-arrow-up'></i>
          </button>
        </div>
      </div>
    </>
  )
}
